
//! WiFi networks SSID and password settings. Update accordingly with the network used
#define SECRET_SSID "HUAWEI P20"
#define SECRET_PASS "cagliostro"

//! AWS IoT broker hostname. It is a unique endpoint generated by the AWS
//! IoT service when you register the thing associated with this program
#define SECRET_BROKER "a2m5vsd3ukfar4-ats.iot.us-east-1.amazonaws.com"

//! MKR1000 board public certificate created by AWS IoT service
//! registering the private cretificate generated by the crypto chi
//! on the board
const char SECRET_CERTIFICATE[] = R"(
-----BEGIN CERTIFICATE-----
MIIC6zCCAdOgAwIBAgIVAPsJfCcRaV/wi2Lpxtu9/OUlV8vLMA0GCSqGSIb3DQEB
CwUAME0xSzBJBgNVBAsMQkFtYXpvbiBXZWIgU2VydmljZXMgTz1BbWF6b24uY29t
IEluYy4gTD1TZWF0dGxlIFNUPVdhc2hpbmd0b24gQz1VUzAeFw0xOTA1MjQwODM2
MzJaFw00OTEyMzEyMzU5NTlaMHoxCzAJBgNVBAYTAkJFMRAwDgYDVQQIEwdCZWxn
aXVtMQ4wDAYDVQQHEwVHaGVudDEaMBgGA1UEChMRQmFsZWFyaWMgRHluYW1pY3Mx
FTATBgNVBAsTDEFydC1hLVRyb25pYzEWMBQGA1UEAxMNU2V2ZW4gT2YgTmluZTBZ
MBMGByqGSM49AgEGCCqGSM49AwEHA0IABApJP0U43nIrNH6me4AkpVCcJgXHzM3k
Q8DYAg3QegBZiXAo+Zy2/1X7WHBTgv9/mTvTAeQEhCpJHinvcohJjP+jYDBeMB8G
A1UdIwQYMBaAFJhuM9nG7uGsWLx7TuUdANtU4uhHMB0GA1UdDgQWBBSLBawI8+Lc
zV0hn08TjbWtMOvjuzAMBgNVHRMBAf8EAjAAMA4GA1UdDwEB/wQEAwIHgDANBgkq
hkiG9w0BAQsFAAOCAQEAa3h0MtwH4MtUhzSUE6ZcVAIl3qAs2SoWPGPyHX9bbX3v
2oubgVl3ie+r/P/8txthkkub256Sx40bH2ar10Hdt5/iE1P6JwN6DaqA8zusAIAq
ujovN90PeVovR3+3njOb+uYdLbMCM9N7BTYMxuVVCaqAuszlSoR5NjW/Rev68NZk
VV7okBtN7DTnRk/2nl3a1iQPcvDDKC1nrpYrpr+HLGEYFws4PgP2i4SNoKTebKvM
hABMhMLPZLb/3p1XWaGUfiqzzhkGPwxyrR7Xo9nZjxRYjoJAieQJHllgJIZC3YnT
s5kwyfjR9omL8rGWT9ggMd0GHjH5yQ4sm9hT9qrOYg==
-----END CERTIFICATE-----
)";
